### ISSUE TITLE
Data Access Request API: Duplicate

### ISSUE THREAD

**Issue by ilyasse005** [Jxck-S/plane-notify#139] opened 2024-08-04 22:34 UTC

**Comment by ilyasse005** [comment] 2024-08-04 22:42
![Uploading Screenshot from 2024-07-25 20-53-02.png…]()

**Comment by ilyasse005** [comment] 2024-08-04 22:43
.

**Comment by Jxck-S** [comment] 2024-11-02 00:11
Duplicate of #138

**Closed as completed by Jxck-S** 2024-11-02 00:11 UTC
